Fix deprecation warnings for Django5.
In preparation for upgrading to Django5, this commit cleans up the
following minor warnings/errors found by running:

```
PYTHONWARNINGS=always uv run coldfront test
```

- ResourceWarning: unclosed file <_io.TextIOWrapper name='.env' mode='r' encoding='UTF-8'>
- RemovedInDjango50Warning: The USE_L10N setting is deprecated. (always
  enabled by default now)
- RemovedInDjango50Warning: The django.utils.timezone.utc alias is deprecated.
- DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead

We also adjust this test case which will error out in Django5:

ERROR: test_project_attribute_create_post_required_values
ProjectAttributeCreate correctly flags missing project or value
----------------------------------------------------------------------
Traceback (most recent call last):
  File "coldfront/core/project/tests/test_views.py", line 174, in test_project_attribute_create_post_required_values
    self.assertFormError(response, "form", "project", "This field is required.")
  File ".venv/lib/python3.12/site-packages/django/test/testcases.py", line 708, in assertFormError
    self._assert_form_error(form, field, errors, msg_prefix, f"form {form!r}")
  File ".venv/lib/python3.12/site-packages/django/test/testcases.py", line 674, in _assert_form_error
    if not form.is_bound:
           ^^^^^^^^^^^^^
AttributeError: 'TemplateResponse' object has no attribute 'is_bound'

The `assertFormError` in SimpleTestCase requires a bound form instance not a
template response. Instead we check the response content to ensure we're still
on the project attribute create page.

Signed-off-by: Andrew E. Bruno <aebruno2@buffalo.edu>